services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 5433
    ports:
      - "5433:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - my_postgres_data:/var/lib/postgresql/data
  
volumes:
  my_postgres_data: