# default redis config
# save 900 1  
# save 300 10 
# save 60 10000 

# my config
# Save if at least 1 change after 60 seconds
save 600 1  
# Save if at least 10 changes after 30 seconds
save 30 10 
# Save if at least 10000 changes after 10 seconds
save 10 10000